import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import LayoutPage from "@/components/layout/layout-page";
import QueryProvider from "@/provider/query-provider";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "3 tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} container mx-auto min-h-screen bg-[#fcfbfa] antialiased`}
      >
        <QueryProvider>
          <LayoutPage>{children}</LayoutPage>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
